<?php
/**
 *
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 *
 * SuiteCRM is an extension to SugarCRM Community Edition developed by SalesAgility Ltd.
 * Copyright (C) 2011 - 2017 SalesAgility Ltd.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo and "Supercharged by SuiteCRM" logo. If the display of the logos is not
 * reasonably feasible for  technical reasons, the Appropriate Legal Notices must
 * display the words  "Powered by SugarCRM" and "Supercharged by SuiteCRM".
 */

$dictionary['DISC_Discovery'] = array(
    'table' => 'disc_discovery',
    'audited' => true,
    'inline_edit' => true,
    'fields' => array (
  'contact_id_c' => 
  array (
    'required' => false,
    'name' => 'contact_id_c',
    'vname' => 'LBL_COMPANION_CONTACT_ID',
    'type' => 'id',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => 0,
    'audited' => false,
    'inline_edit' => true,
    'reportable' => false,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 36,
    'size' => '20',
  ),
  'companion' => 
  array (
    'required' => false,
    'source' => 'non-db',
    'name' => 'companion',
    'vname' => 'LBL_COMPANION',
    'type' => 'relate',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => 'visible if case type contains &quot;Companion&quot;',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
    'id_name' => 'contact_id_c',
    'ext2' => 'Contacts',
    'module' => 'Contacts',
    'rname' => 'name',
    'quicksearch' => 'enabled',
    'studio' => 'visible',
  ),
  'date_served' => 
  array (
    'required' => false,
    'name' => 'date_served',
    'vname' => 'LBL_DATE_SERVED',
    'type' => 'date',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'enable_range_search' => false,
  ),
  'status_id' => 
  array (
    'name' => 'status_id',
    'vname' => 'LBL_DOC_STATUS',
    'type' => 'enum',
    'len' => 100,
    'options' => 'disc_status_list',
    'reportable' => true,
    'required' => false,
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'type' => 
  array (
    'required' => false,
    'name' => 'type',
    'vname' => 'LBL_TYPE',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'disc_type_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'done' => 
  array (
    'required' => false,
    'name' => 'done',
    'vname' => 'LBL_DONE',
    'type' => 'bool',
    'massupdate' => true,
    'default' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'next_step' => 
  array (
    'required' => false,
    'name' => 'next_step',
    'vname' => 'LBL_NEXT_STEP',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'disc_status_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'parent_name' => 
  array (
    'required' => true,
    'source' => 'non-db',
    'name' => 'parent_name',
    'vname' => 'LBL_FLEX_RELATE',
    'type' => 'parent',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 25,
    'size' => '20',
    'options' => 'parent_type_display',
    'studio' => 'visible',
    'type_name' => 'parent_type',
    'id_name' => 'parent_id',
    'parent_type' => 'record_type_display',
  ),
  'parent_type' => 
  array (
    'required' => false,
    'name' => 'parent_type',
    'vname' => 'LBL_PARENT_TYPE',
    'type' => 'parent_type',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => 0,
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 255,
    'size' => '20',
    'dbType' => 'varchar',
    'studio' => 'hidden',
  ),
  'parent_id' => 
  array (
    'required' => false,
    'name' => 'parent_id',
    'vname' => 'LBL_PARENT_ID',
    'type' => 'id',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => 0,
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 36,
    'size' => '20',
  ),
  'q_a' => 
  array (
    'required' => false,
    'name' => 'q_a',
    'vname' => 'LBL_Q_A',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'q_a_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'response_date' => 
  array (
    'required' => false,
    'name' => 'response_date',
    'vname' => 'LBL_RESPONSE_DATE',
    'type' => 'date',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'enable_range_search' => false,
  ),
  'sent_received' => 
  array (
    'required' => false,
    'name' => 'sent_received',
    'vname' => 'LBL_SENT_RECEIVED',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'sent_received_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'account_id_c' => 
  array (
    'required' => false,
    'name' => 'account_id_c',
    'vname' => 'LBL_TO_FROM_ACCOUNT_ID',
    'type' => 'id',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => 0,
    'audited' => false,
    'inline_edit' => true,
    'reportable' => false,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 36,
    'size' => '20',
  ),
  'to_from' => 
  array (
    'required' => false,
    'source' => 'non-db',
    'name' => 'to_from',
    'vname' => 'LBL_TO_FROM',
    'type' => 'relate',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
    'id_name' => 'account_id_c',
    'ext2' => 'Accounts',
    'module' => 'Accounts',
    'rname' => 'name',
    'quicksearch' => 'enabled',
    'studio' => 'visible',
  ),
  'date_of_incident' => 
  array (
    'required' => false,
    'name' => 'date_of_incident',
    'vname' => 'LBL_DATE_OF_INCIDENT',
    'type' => 'date',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => 'visible if case type equals Multiple Claims in One',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'enable_range_search' => false,
  ),
  'assigned_lawyer_cases' => 
  array (
	'name' => 'assigned_lawyer_cases',
	'label' => 'LBL_ASSIGNED_LAWYER_CASES',
	'type' => 'enum',
	'source' => 'non-db',
	'options' => 'assigned_lawyer_cases_list',
  ),
   'case_status' => 
	  array (
		 'name' => 'case_status',
		  'vname' => 'LBL_STATUS',
		  'type' => 'enum',
		  'source' => 'non-db',
		  'options' => 'case_status_dom',
	  ),
	'hd_reviewed_by' => 
    array (
      'inline_edit' => 1,
      'required' => false,
      'name' => 'hd_reviewed_by',
      'vname' => 'LBL_HD_REVIEWED_BY',
      'type' => 'id',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => false,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '36',
      'size' => '20',
    ),
    'hd_reviewed_by_name' => 
    array (
      'inline_edit' => '1',
      'required' => false,
      'source' => 'non-db',
      'name' => 'hd_reviewed_by_name',
      'vname' => 'LBL_HD_REVIEWED_BY',
      'type' => 'relate',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id_name' => 'hd_reviewed_by',
      'ext2' => 'Users',
      'module' => 'Users',
      'rname' => 'name',
      'quicksearch' => 'enabled',
      'studio' => 'visible',
    ),
	'hd_reviewed_date' => 
    array (
      'name' => 'hd_reviewed_date',
      'vname' => 'LBL_HD_REVIEWED_DATE',
      'type' => 'date',
      'required' => false,
      'importable' => 'required',
      'display_default' => 'now',
      'inline_edit' => true,
      'merge_filter' => 'disabled',
      'enable_range_search' => false,
    ),
	'related_case_assigned_to' => array(
		'name' => 'related_case_assigned_to',
		'vname' => 'LBL_RELATED_CASE_ASSIGNED_TO',
		'type' => 'varchar',
		'len' => '255',
		'source' => 'non-db',
		'function' => array('name'=>'getrelated_discovery_case_assigned_to',
					 'returns'=>'html',
					 'include'=>'custom/include/custom_utils.php'),
	),
	'duration' =>
	array(
		'name' => 'duration',
		'vname' => 'LBL_DURATION',
		'type' => 'enum',
		'source' => 'non-db',
		'options' => 'duration_dom',
		'source' => 'non-db',
		'comment' => 'Duration handler dropdown',
		'massupdate' => false,
		'reportable' => false,
		'importable' => false,
	),
	'date_start' =>
		array(
			'name' => 'date_start',
			'vname' => 'LBL_DATE',
			'type' => 'datetimecombo',
			'source' => 'non-db',
			'comment' => 'Date of start of meeting',
			'importable' => 'required',
			'required' => false,
			'enable_range_search' => true,
			'options' => 'date_range_search_dom',
			'validation' => array('type' => 'isbefore', 'compareto' => 'date_end', 'blank' => false),
		),
	'duration_hours' =>
		array(
			'name' => 'duration_hours',
			'vname' => 'LBL_DURATION_HOURS',
			'type' => 'int',
			'source' => 'non-db',
			'group' => 'duration',
			'len' => '3',
			'comment' => 'Duration (hours)',
			'importable' => 'required',
			'required' => false,
		),
    'duration_minutes' =>
		array(
			'name' => 'duration_minutes',
			'vname' => 'LBL_DURATION_MINUTES',
			'type' => 'int',
			'source' => 'non-db',
			'group' => 'duration',
			'len' => '2',
			'comment' => 'Duration (minutes)',
		),
    'date_end' =>
		array(
			'name' => 'date_end',
			'vname' => 'LBL_DATE_END',
			'type' => 'datetimecombo',
			'dbType' => 'datetime',
			'source' => 'non-db',
			'massupdate' => false,
			'comment' => 'Date meeting ends',
			'enable_range_search' => true,
			'options' => 'date_range_search_dom',
		),
	'events_multiple_assigned_users' => 
		array (
		  'name' => 'events_multiple_assigned_users',
		  'vname' => 'LBL_MULTIPLE_ASSIGNED_USERS',
		  'type' => 'multienum',
		  'options' => 'multiple_assigned_users_list',
		  'function' => 'get_users',
		  'required' => false,
		),
	'type_c' => 
		array (
		  'required' => false,
		  'name' => 'type_c',
		  'vname' => 'LBL_PURPOSE',
		  'type' => 'enum',
		  'source' => 'non-db',
		  'options' => 'event_type_list',
		),
	'event_type' => 
		array(
			'required' => false,
			'name' => 'event_type',
			'vname' => 'LBL_EVENT_TYPE',
			'type' => 'enum',
			'source' => 'non-db',
			'options' => 'event_type_new_list',
		),
	'author_type' => 
		array (
		  'name' => 'author_type',
		  'vname' => 'LBL_AUTHOR_TYPE',
		  'type' => 'enum',
		  'options' => 'author_type_list',
		  'required' => true,
		),
	'document_processed_description' => 
		array (
		  'name' => 'document_processed_description',
		  'vname' => 'LBL_DOCUMENT_PROCESSED_DESCRIPTION',
		  'type' => 'text',
		  'len' => '155',
		  'size' => '155',
		  'rows' => 6,
		  'cols' => 80,
		),
	'discovery_description' => 
    array (
      'name' => 'discovery_description',
      'vname' => 'LBL_DISCOVERY_DESCRIPTION',
      'type' => 'text',
      'merge_filter' => 'disabled',
      'rows' => '1',
      'cols' => '20',
	  'required' => false,
    ),
	'related_case_assistant' => array(
		'name' => 'related_case_assistant',
		'vname' => 'LBL_RELATED_CASE_ASSISTANT',
		'type' => 'varchar',
		'source' => 'non-db',
	),
),
    'relationships' => array (
),
    'optimistic_locking' => true,
    'unified_search' => true,
);
if (!class_exists('VardefManager')) {
        require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('DISC_Discovery', 'DISC_Discovery', array('basic','assignable','security_groups','file'));