<?php
/**
 *
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 *
 * SuiteCRM is an extension to SugarCRM Community Edition developed by SalesAgility Ltd.
 * Copyright (C) 2011 - 2017 SalesAgility Ltd.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo and "Supercharged by SuiteCRM" logo. If the display of the logos is not
 * reasonably feasible for  technical reasons, the Appropriate Legal Notices must
 * display the words  "Powered by SugarCRM" and "Supercharged by SuiteCRM".
 */

$dictionary['NEG_Negotiations'] = array(
    'table' => 'neg_negotiations',
    'audited' => true,
    'inline_edit' => true,
    'fields' => array (
  'contact_id_c' => 
  array (
    'required' => false,
    'name' => 'contact_id_c',
    'vname' => 'LBL_ADJUSTER_LAWYER_CONTACT_ID',
    'type' => 'id',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => 0,
    'audited' => false,
    'inline_edit' => true,
    'reportable' => false,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 36,
    'size' => '20',
  ),
  'adjuster_lawyer' => 
  array (
    'required' => false,
    'source' => 'non-db',
    'name' => 'adjuster_lawyer',
    'vname' => 'LBL_ADJUSTER_LAWYER',
    'type' => 'relate',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
    'id_name' => 'contact_id_c',
    'ext2' => 'Contacts',
    'module' => 'Contacts',
    'rname' => 'name',
    'quicksearch' => 'enabled',
    'studio' => 'visible',
  ),
  'amount' => 
  array (
    'required' => false,
    'name' => 'amount',
    'vname' => 'LBL_AMOUNT',
    'type' => 'currency',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 26,
    'size' => '20',
    'enable_range_search' => false,
    'precision' => 6,
  ),
  'currency_id' => 
  array (
    'required' => false,
    'name' => 'currency_id',
    'vname' => 'LBL_CURRENCY',
    'type' => 'currency_id',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => 0,
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 36,
    'size' => '20',
    'dbType' => 'id',
    'studio' => 'visible',
    'function' => 
    array (
      'name' => 'getCurrencyDropDown',
      'returns' => 'html',
    ),
  ),
  'contact_id1_c' => 
  array (
    'required' => false,
    'name' => 'contact_id1_c',
    'vname' => 'LBL_COMPANION_CONTACT_ID',
    'type' => 'id',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => 0,
    'audited' => false,
    'inline_edit' => true,
    'reportable' => false,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 36,
    'size' => '20',
  ),
  'companion' => 
  array (
    'required' => false,
    'source' => 'non-db',
    'name' => 'companion',
    'vname' => 'LBL_COMPANION',
    'type' => 'relate',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
    'id_name' => 'contact_id1_c',
    'ext2' => 'Contacts',
    'module' => 'Contacts',
    'rname' => 'name',
    'quicksearch' => 'enabled',
    'studio' => 'visible',
  ),
  'contact_id2_c' => 
  array (
    'required' => false,
    'name' => 'contact_id2_c',
    'vname' => 'LBL_DEFENDANT_CONTACT_ID',
    'type' => 'id',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => 0,
    'audited' => false,
    'inline_edit' => true,
    'reportable' => false,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 36,
    'size' => '20',
  ),
  'defendant' => 
  array (
    'required' => false,
    'source' => 'non-db',
    'name' => 'defendant',
    'vname' => 'LBL_DEFENDANT',
    'type' => 'relate',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
    'id_name' => 'contact_id2_c',
    'ext2' => 'Contacts',
    'module' => 'Contacts',
    'rname' => 'name',
    'quicksearch' => 'enabled',
    'studio' => 'visible',
  ),
    'parent_type'=> array(
		'name'=>'parent_type',
		'vname'=>'LBL_PARENT_TYPE',
		'type' =>'parent_type',
		'dbType' => 'varchar',
		'group'=>'parent_name',
		'options'=> 'parent_type_display',
		'len'=> '255',
		'comment' => 'Sugar module the Note is associated with'
	),

	'parent_id'=>array(
		'name'=>'parent_id',
		'vname'=>'LBL_PARENT_ID',
		'type'=>'id',
		'required'=>false,
		'reportable'=>true,
		'comment' => 'The ID of the Sugar item specified in parent_type'
	),

	 'parent_name'=>array(
		'required'=>true,
		'name'=> 'parent_name',
		'parent_type'=>'record_type_display' ,
		'type_name'=>'parent_type',
		'id_name'=>'parent_id',
		'vname'=>'LBL_DEFENDANT',
		'type'=>'parent',
		'source'=>'non-db',
		'options'=> 'location_type_dom',
	),
  'account_id_c' => 
  array (
    'required' => false,
    'name' => 'account_id_c',
    'vname' => 'LBL_INSURANCE_COMPANY_ACCOUNT_ID',
    'type' => 'id',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => 0,
    'audited' => false,
    'inline_edit' => true,
    'reportable' => false,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 36,
    'size' => '20',
  ),
  'insurance_company' => 
  array (
    'required' => false,
    'source' => 'non-db',
    'name' => 'insurance_company',
    'vname' => 'LBL_INSURANCE_COMPANY',
    'type' => 'relate',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
    'id_name' => 'account_id_c',
    'ext2' => 'Accounts',
    'module' => 'Accounts',
    'rname' => 'name',
    'quicksearch' => 'enabled',
    'studio' => 'visible',
  ),
  'mode' => 
  array (
    'required' => false,
    'name' => 'mode',
    'vname' => 'LBL_MODE',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => 'How was the negotiation communicated',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'neg_mode_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'response' => 
  array (
    'required' => false,
    'name' => 'response',
    'vname' => 'LBL_RESPONSE',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'response_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'sent_rec' => 
  array (
    'required' => false,
    'name' => 'sent_rec',
    'vname' => 'LBL_SENT_REC',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'sent_received_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'type' => 
  array (
    'required' => false,
    'name' => 'type',
    'vname' => 'LBL_TYPE',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'neg_type_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'initial_counter' => 
  array (
    'required' => false,
    'name' => 'initial_counter',
    'vname' => 'LBL_INITIAL_COUNTER',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'initial_counter_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'assigned_lawyer_cases' => 
  array (
	'name' => 'assigned_lawyer_cases',
	'label' => 'LBL_ASSIGNED_LAWYER_CASES',
	'type' => 'enum',
	'source' => 'non-db',
	'options' => 'assigned_lawyer_cases_list',
  ),
  'case_status' => 
      array (
         'name' => 'case_status',
		  'vname' => 'LBL_STATUS',
		  'type' => 'enum',
		  'source' => 'non-db',
		  'options' => 'case_status_dom',
      ),
	'done' => 
		array (
			'required' => false,
			'name' => 'done',
			'vname' => 'LBL_DONE',
			'type' => 'bool',
			'massupdate' => true,
			'default' => '0',
			'no_default' => false,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'inline_edit' => true,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => '255',
			'size' => '20',
		),
	'hd_reviewed_by' => 
    array (
      'inline_edit' => 1,
      'required' => false,
      'name' => 'hd_reviewed_by',
      'vname' => 'LBL_HD_REVIEWED_BY',
      'type' => 'id',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => false,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '36',
      'size' => '20',
    ),
    'hd_reviewed_by_name' => 
    array (
      'inline_edit' => '1',
      'required' => false,
      'source' => 'non-db',
      'name' => 'hd_reviewed_by_name',
      'vname' => 'LBL_HD_REVIEWED_BY',
      'type' => 'relate',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id_name' => 'hd_reviewed_by',
      'ext2' => 'Users',
      'module' => 'Users',
      'rname' => 'name',
      'quicksearch' => 'enabled',
      'studio' => 'visible',
    ),
	'hd_reviewed_date' => 
    array (
      'name' => 'hd_reviewed_date',
      'vname' => 'LBL_HD_REVIEWED_DATE',
      'type' => 'date',
      'required' => false,
      'importable' => 'required',
      'display_default' => 'now',
      'inline_edit' => true,
      'merge_filter' => 'disabled',
      'enable_range_search' => false,
    ),	
	/* 'offer_expires' => 
    array (
      'name' => 'offer_expires',
      'vname' => 'LBL_OFFER_EXPIRES',
      'type' => 'datetimecombo',
      'dbType' => 'datetime',
      'required' => false,
      'importable' => 'required',
      'inline_edit' => true,
      'merge_filter' => 'disabled',
      'enable_range_search' => false,
    ), */
	'related_case_assigned_to' => array(
		'name' => 'related_case_assigned_to',
		'vname' => 'LBL_RELATED_CASE_ASSIGNED_TO',
		'type' => 'varchar',
		'len' => '255',
		'source' => 'non-db',
		'function' => array('name'=>'getrelated_neg_negotiations_case_assigned_to',
					 'returns'=>'html',
					 'include'=>'custom/include/custom_utils.php'),
	),
	'related_case_assistant' => array(
		'name' => 'related_case_assistant',
		'vname' => 'LBL_RELATED_CASE_ASSISTANT',
		'type' => 'varchar',
		'source' => 'non-db',
	),
	'multiple_assigned_users' => 
		array (
		  'name' => 'multiple_assigned_users',
		  'vname' => 'LBL_MULTIPLE_ASSIGNED_USERS',
		  'type' => 'multienum',
		  'options' => 'multiple_assigned_users_list',
		  'function' => 'get_users',
		),
	'duration' =>
		array(
			'name' => 'duration',
			'vname' => 'LBL_DURATION',
			'type' => 'enum',
			'source' => 'non-db',
			'options' => 'duration_dom',
			'source' => 'non-db',
			'comment' => 'Duration handler dropdown',
			'massupdate' => false,
			'reportable' => false,
			'importable' => false,
		),
	'date_start' =>
		array(
			'name' => 'date_start',
			'vname' => 'LBL_DATE',
			'type' => 'datetimecombo',
			'source' => 'non-db',
			'comment' => 'Date of start of meeting',
			'importable' => 'required',
			'required' => false,
			'enable_range_search' => true,
			'options' => 'date_range_search_dom',
			'validation' => array('type' => 'isbefore', 'compareto' => 'date_end', 'blank' => false),
		),
	'duration_hours' =>
		array(
			'name' => 'duration_hours',
			'vname' => 'LBL_DURATION_HOURS',
			'type' => 'int',
			'source' => 'non-db',
			'group' => 'duration',
			'len' => '3',
			'comment' => 'Duration (hours)',
			'importable' => 'required',
			'required' => false,
		),
    'duration_minutes' =>
		array(
			'name' => 'duration_minutes',
			'vname' => 'LBL_DURATION_MINUTES',
			'type' => 'int',
			'source' => 'non-db',
			'group' => 'duration',
			'len' => '2',
			'comment' => 'Duration (minutes)',
		),
    'date_end' =>
		array(
			'name' => 'date_end',
			'vname' => 'LBL_DATE_END',
			'type' => 'datetimecombo',
			'dbType' => 'datetime',
			'source' => 'non-db',
			'massupdate' => false,
			'comment' => 'Date meeting ends',
			'enable_range_search' => true,
			'options' => 'date_range_search_dom',
		),
	'type_c' => 
		array (
		  'required' => false,
		  'name' => 'type_c',
		  'vname' => 'LBL_TYPE',
		  'type' => 'enum',
		  'source' => 'non-db',
		  'options' => 'event_type_list',
		),
	'event_type' => 
		array(
			'required' => false,
			'name' => 'event_type',
			'vname' => 'LBL_EVENT_TYPE',
			'type' => 'enum',
			'source' => 'non-db',
			'options' => 'event_type_new_list',
		),
	'events_multiple_assigned_users' => 
		array (
		  'name' => 'events_multiple_assigned_users',
		  'vname' => 'LBL_MULTIPLE_ASSIGNED_USERS',
		  'type' => 'multienum',
		  'options' => 'multiple_assigned_users_list',
		  'function' => 'get_users',
		  'required' => false,
		),
),
    'relationships' => array (
),
    'optimistic_locking' => true,
    'unified_search' => true,
);
if (!class_exists('VardefManager')) {
        require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('NEG_Negotiations', 'NEG_Negotiations', array('basic','assignable','security_groups','file'));
