<?php
/**
 *
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 *
 * SuiteCRM is an extension to SugarCRM Community Edition developed by SalesAgility Ltd.
 * Copyright (C) 2011 - 2017 SalesAgility Ltd.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo and "Supercharged by SuiteCRM" logo. If the display of the logos is not
 * reasonably feasible for  technical reasons, the Appropriate Legal Notices must
 * display the words  "Powered by SugarCRM" and "Supercharged by SuiteCRM".
 */

$dictionary['DEF_Defendants'] = array(
    'table' => 'def_defendants',
    'audited' => true,
    'inline_edit' => true,
    'duplicate_merge' => true,
    'fields' => array (
  'type' => 
  array (
    'required' => false,
    'name' => 'type',
    'vname' => 'LBL_TYPE',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'type_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'contact_id_c' => 
  array (
    'required' => false,
    'name' => 'contact_id_c',
    'vname' => 'LBL_ADJUSTER_CONTACT_ID',
    'type' => 'id',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => 0,
    'audited' => false,
    'inline_edit' => true,
    'reportable' => false,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 36,
    'size' => '20',
  ),
  'adjuster' => 
  array (
    'required' => false,
    'source' => 'non-db',
    'name' => 'adjuster',
    'vname' => 'LBL_ADJUSTER',
    'type' => 'relate',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
    'id_name' => 'contact_id_c',
    'ext2' => 'Contacts',
    'module' => 'Contacts',
    'rname' => 'name',
    'quicksearch' => 'enabled',
    'studio' => 'visible',
  ),
  'account_id_c' => 
  array (
    'required' => false,
    'name' => 'account_id_c',
    'vname' => 'LBL_INSURANCE_COMPANY_ACCOUNT_ID',
    'type' => 'id',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => 0,
    'audited' => false,
    'inline_edit' => true,
    'reportable' => false,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 36,
    'size' => '20',
  ),
  'insurance_company' => 
  array (
    'required' => false,
    'source' => 'non-db',
    'name' => 'insurance_company',
    'vname' => 'LBL_INSURANCE_COMPANY',
    'type' => 'relate',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
    'id_name' => 'account_id_c',
    'ext2' => 'Accounts',
    'module' => 'Accounts',
    'rname' => 'name',
    'quicksearch' => 'enabled',
    'studio' => 'visible',
  ),
  'policy_type' => 
  array (
    'required' => false,
    'name' => 'policy_type',
    'vname' => 'LBL_POLICY_TYPE',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'policy_type_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'claim_number' => 
  array (
    'required' => false,
    'name' => 'claim_number',
    'vname' => 'LBL_CLAIM_NUMBER',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '20',
    'size' => '20',
  ),
  'contact_id1_c' => 
  array (
    'required' => false,
    'name' => 'contact_id1_c',
    'vname' => 'LBL_DEFENDANT_CONTACT_ID',
    'type' => 'id',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => 0,
    'audited' => false,
    'inline_edit' => true,
    'reportable' => false,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 36,
    'size' => '20',
  ),
  'defendant' => 
  array (
    'required' => false,
    'source' => 'non-db',
    'name' => 'defendant',
    'vname' => 'LBL_DEFENDANT',
    'type' => 'relate',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
    'id_name' => 'contact_id1_c',
    'ext2' => 'Contacts',
    'module' => 'Contacts',
    'rname' => 'fmls_name',
    'quicksearch' => 'enabled',
    'studio' => 'visible',
  ),
  'human_def_last_name' => 
  array (
    'required' => false,
    'source' => 'non-db',
    'name' => 'human_def_last_name',
    'vname' => 'LBL_HUMAN_DEF_LAST_NAME',
    'type' => 'relate',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
    'id_name' => 'contact_id1_c',
    'ext2' => 'Contacts',
    'module' => 'Contacts',
    'rname' => 'last_name',
    'quicksearch' => 'enabled',
    'studio' => 'visible',
  ),
  'human_def_birthdate' => 
  array (
    'required' => false,
    'source' => 'non-db',
    'name' => 'human_def_birthdate',
    'vname' => 'LBL_HUMAN_DEF_BIRTHDATE',
    'type' => 'relate',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
    'id_name' => 'contact_id1_c',
    'ext2' => 'Contacts',
    'module' => 'Contacts',
    'rname' => 'birthdate',
    'quicksearch' => 'enabled',
    'studio' => 'visible',
  ), 
  'human_def_drivers_license_no' => 
  array (
    'required' => false,
    'source' => 'non-db',
    'name' => 'human_def_drivers_license_no',
    'vname' => 'LBL_HUMAN_DEF_DRIVERS_LICENSE_NO',
    'type' => 'relate',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
    'id_name' => 'contact_id1_c',
    'ext2' => 'Contacts',
    'module' => 'Contacts',
    'rname' => 'drivers_license_c',
    'quicksearch' => 'enabled',
    'studio' => 'visible',
  ),
  'human_def_full_address' => 
  array (
    'required' => false,
    'source' => 'non-db',
    'name' => 'human_def_full_address',
    'vname' => 'LBL_HUMAN_DEF_FULL_ADDRESS',
    'type' => 'relate',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
    'id_name' => 'contact_id1_c',
    'ext2' => 'Contacts',
    'module' => 'Contacts',
    'rname' => 'full_address',
    'quicksearch' => 'enabled',
    'studio' => 'visible',
  ),
  'defendant_organization_full_address' => 
  array (
    'required' => false,
    'source' => 'non-db',
    'name' => 'defendant_organization_full_address',
    'vname' => 'LBL_DEFENDANT_ORGANIZATION_FULL_ADDRESS',
    'type' => 'relate',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
    'id_name' => 'account_id1_c',
    'ext2' => 'Accounts',
    'module' => 'Accounts',
    'rname' => 'full_address',
    'quicksearch' => 'enabled',
    'studio' => 'visible',
  ),
   'account_id1_c' => 
    array (
      'inline_edit' => 1,
      'required' => false,
      'name' => 'account_id1_c',
      'vname' => 'LBL_DEFENDANT_ORGANIZATION_ACCOUNT_ID',
      'type' => 'id',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => false,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '36',
      'size' => '20',
    ),
  'policy_limits' => 
  array (
    'required' => false,
    'name' => 'policy_limits',
    'vname' => 'LBL_POLICY_LIMITS',
    'type' => 'currency',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 26,
    'size' => '20',
    'enable_range_search' => false,
    'precision' => 6,
  ),
  'currency_id' => 
  array (
    'required' => false,
    'name' => 'currency_id',
    'vname' => 'LBL_CURRENCY',
    'type' => 'currency_id',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => 0,
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 36,
    'size' => '20',
    'dbType' => 'id',
    'studio' => 'visible',
    'function' => 
    array (
      'name' => 'getCurrencyDropDown',
      'returns' => 'html',
    ),
  ),
  'claim_result' => 
  array (
    'required' => false,
    'name' => 'claim_result',
    'vname' => 'LBL_CLAIM_RESULT',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'claim_result_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'lit_spot' => 
  array (
    'required' => false,
    'name' => 'lit_spot',
    'vname' => 'LBL_LIT_SPOT',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'lit_spot_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'date_of_incident' => 
  array (
    'required' => false,
    'name' => 'date_of_incident',
    'vname' => 'LBL_DATE_OF_INCIDENT',
    'type' => 'date',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => 'visible if case type equals Multiple Claims in One',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'enable_range_search' => false,
  ),
    'assigned_lawyer_cases' => 
  array (
	'name' => 'assigned_lawyer_cases',
	'label' => 'LBL_ASSIGNED_LAWYER_CASES',
	'type' => 'enum',
	'source' => 'non-db',
	'options' => 'assigned_lawyer_cases_list',
  ),
    'case_status' => 
  array (
	 'name' => 'case_status',
	  'vname' => 'LBL_STATUS',
	  'type' => 'enum',
	  'source' => 'non-db',
	  'options' => 'case_status_dom',
  ),
   'acase_id' =>
		array(
			'required' => false,
			'name' => 'acase_id',
			'vname' => '',
			'type' => 'id',
			'massupdate' => 0,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => 0,
			'audited' => 0,
			'reportable' => 0,
			'len' => 36,
		),
    'acase_name' =>
		array(
			'required' => true,
			'source' => 'non-db',
			'name' => 'acase_name',
			'vname' => 'LBL_ACASE_NAME',
			'type' => 'relate',
			'massupdate' => 0,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => 1,
			'reportable' => 1,
			'len' => '255',
			'id_name' => 'acase_id',
			'ext2' => 'Cases',
			'module' => 'Cases',
			'quicksearch' => 'enabled',
			'studio' => 'visible',
			'link' => 'def_defendants_cases',
		),
		
		'complaint_id' =>
		array(
			'required' => false,
			'name' => 'complaint_id',
			'vname' => '',
			'type' => 'id',
			'massupdate' => 0,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => 0,
			'audited' => 0,
			'reportable' => 0,
			'len' => 36,
		),
    'complain_name' =>
		array(
			'required' => true,
			'source' => 'non-db',
			'name' => 'complain_name',
			'vname' => 'LBL_COMPLAINT_NAME',
			'type' => 'relate',
			'massupdate' => 0,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => 1,
			'reportable' => 1,
			'len' => '255',
			'id_name' => 'complaint_id',
			'ext2' => 'Complaints',
			'module' => 'Complaints',
			'quicksearch' => 'enabled',
			'studio' => 'visible',
			'link' => 'def_defendants_complaints',
		),
	'adjuster_primary_address_street' => 
  array (
    'required' => false,
    'source' => 'non-db',
    'name' => 'adjuster_primary_address_street',
    'vname' => 'LBL_ADJUSTER_PRIMARY_ADDRESS_STREET',
    'type' => 'relate',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
    'id_name' => 'contact_id_c',
    'ext2' => 'Contacts',
    'module' => 'Contacts',
    'rname' => 'primary_address_street',
    'quicksearch' => 'enabled',
    'studio' => 'visible',
  ), 
  'adjuster_dear' => 
  array (
    'required' => false,
    'source' => 'non-db',
    'name' => 'adjuster_dear',
    'vname' => 'LBL_ADJUSTER_DEAR',
    'type' => 'relate',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
    'id_name' => 'contact_id_c',
    'ext2' => 'Contacts',
    'module' => 'Contacts',
    'rname' => 'dear_c',
    'quicksearch' => 'enabled',
    'studio' => 'visible',
  ), 
  'adjuster_primary_address_city' => 
  array (
    'required' => false,
    'source' => 'non-db',
    'name' => 'adjuster_primary_address_city',
    'vname' => 'LBL_ADJUSTER_PRIMARY_ADDRESS_CITY',
    'type' => 'relate',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
    'id_name' => 'contact_id_c',
    'ext2' => 'Contacts',
    'module' => 'Contacts',
    'rname' => 'primary_address_city',
    'quicksearch' => 'enabled',
    'studio' => 'visible',
  ),
  'adjuster_primary_address_state' => 
  array (
    'required' => false,
    'source' => 'non-db',
    'name' => 'adjuster_primary_address_state',
    'vname' => 'LBL_ADJUSTER_PRIMARY_ADDRESS_STATE',
    'type' => 'relate',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
    'id_name' => 'contact_id_c',
    'ext2' => 'Contacts',
    'module' => 'Contacts',
    'rname' => 'primary_address_state',
    'quicksearch' => 'enabled',
    'studio' => 'visible',
  ),
  
  'adjuster_primary_address_postalcode' => 
  array (
    'required' => false,
    'source' => 'non-db',
    'name' => 'adjuster_primary_address_postalcode',
    'vname' => 'LBL_ADJUSTER_PRIMARY_ADDRESS_POSTALCODE',
    'type' => 'relate',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
    'id_name' => 'contact_id_c',
    'ext2' => 'Contacts',
    'module' => 'Contacts',
    'rname' => 'primary_address_postalcode',
    'quicksearch' => 'enabled',
    'studio' => 'visible',
  ), 
  'adjuster_phone_fax' => 
  array (
    'required' => false,
    'source' => 'non-db',
    'name' => 'adjuster_phone_fax',
    'vname' => 'LBL_ADJUSTER_PHONE_FAX',
    'type' => 'relate',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
    'id_name' => 'contact_id_c',
    'ext2' => 'Contacts',
    'module' => 'Contacts',
    'rname' => 'phone_fax',
    'quicksearch' => 'enabled',
    'studio' => 'visible',
  ),
  'defense_attorney_phone_fax' => 
  array (
    'required' => false,
    'source' => 'non-db',
    'name' => 'defense_attorney_phone_fax',
    'vname' => 'LBL_DEFENSE_ATTORNEY_PHONE_FAX',
    'type' => 'relate',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
    'id_name' => 'contact_id4_c',
    'ext2' => 'Contacts',
    'module' => 'Contacts',
    'rname' => 'phone_fax',
    'quicksearch' => 'enabled',
    'studio' => 'visible',
  ),
   'contact_id4_c' => 
    array (
      'inline_edit' => 1,
      'required' => false,
      'name' => 'contact_id4_c',
      'vname' => 'LBL_DEFENSE_ATTORNEY_CONTACT_ID',
      'type' => 'id',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => false,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '36',
      'size' => '20',
    ),
	
	'defense_attorney_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Defense Attorney',
      'required' => false,
      'source' => 'non-db',
      'name' => 'defense_attorney_c',
      'vname' => 'LBL_DEFENSE_ATTORNEY',
      'type' => 'relate',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => 'The attorney defending this claim',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id_name' => 'contact_id4_c',
      'ext2' => 'Contacts',
      'module' => 'Contacts',
      'rname' => 'name',
      'quicksearch' => 'enabled',
      'studio' => 'visible',
    ),
	'defense_attorney_primary_address_street' => 
  array (
    'required' => false,
    'source' => 'non-db',
    'name' => 'defense_attorney_primary_address_street',
    'vname' => 'LBL_DEFENSE_ATTORNEY_PRIMARY_ADDRESS_STREET',
    'type' => 'relate',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
    'id_name' => 'contact_id4_c',
    'ext2' => 'Contacts',
    'module' => 'Contacts',
    'rname' => 'primary_address_street',
    'quicksearch' => 'enabled',
    'studio' => 'visible',
  ),
  'defense_attorney_account_name' => 
  array (
    'required' => false,
    'name' => 'defense_attorney_account_name',
    'vname' => 'LBL_DEFENSE_ATTORNEY_ACCOUNT_NAME',
	'source' => 'non-db',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
	'type' => 'varchar',
    'len' => '255',
    'size' => '20',
  ), 
  'defense_attorney_primary_address_city' => 
  array (
    'required' => false,
    'source' => 'non-db',
    'name' => 'defense_attorney_primary_address_city',
    'vname' => 'LBL_DEFENSE_ATTORNEY_PRIMARY_ADDRESS_CITY',
    'type' => 'relate',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
    'id_name' => 'contact_id4_c',
    'ext2' => 'Contacts',
    'module' => 'Contacts',
    'rname' => 'primary_address_city',
    'quicksearch' => 'enabled',
    'studio' => 'visible',
  ),
  'defense_attorney_primary_address_state' => 
  array (
    'required' => false,
    'source' => 'non-db',
    'name' => 'defense_attorney_primary_address_state',
    'vname' => 'LBL_DEFENSE_ATTORNEY_PRIMARY_ADDRESS_STATE',
    'type' => 'relate',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
    'id_name' => 'contact_id4_c',
    'ext2' => 'Contacts',
    'module' => 'Contacts',
    'rname' => 'primary_address_state',
    'quicksearch' => 'enabled',
    'studio' => 'visible',
  ),
  'defense_attorney_primary_address_postalcode' => 
  array (
    'required' => false,
    'source' => 'non-db',
    'name' => 'defense_attorney_primary_address_postalcode',
    'vname' => 'LBL_DEFENSE_ATTORNEY_PRIMARY_ADDRESS_POSTALCODE',
    'type' => 'relate',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
    'id_name' => 'contact_id4_c',
    'ext2' => 'Contacts',
    'module' => 'Contacts',
    'rname' => 'primary_address_postalcode',
    'quicksearch' => 'enabled',
    'studio' => 'visible',
  ),
	
),
    'relationships' => array (
),
    'optimistic_locking' => true,
    'unified_search' => true,
);
if (!class_exists('VardefManager')) {
        require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('DEF_Defendants', 'DEF_Defendants', array('basic','assignable','security_groups'));
