<?php
$dictionary['MEDB_Medical_Bills']['fields']['case_new_case_number_c'] = array(
	'inline_edit' => '1',
	'labelValue' => 'CASE_NEW_CASE_NUMBER_C',
	'required' => false,
	'source' => 'non-db',
	'name' => 'case_new_case_number_c',
	'vname' => 'LBL_CASE_NEW_CASE_NUMBER_C',
	'type' => 'relate',
	'massupdate' => '0',
	'default' => NULL,
	'no_default' => false,
	'comments' => '',
	'help' => '',
	'importable' => 'true',
	'duplicate_merge' => 'disabled',
	'duplicate_merge_dom_value' => '0',
	'audited' => false,
	'reportable' => true,
	'unified_search' => false,
	'merge_filter' => 'disabled',
	'len' => '255',
	'size' => '20',
	'id_name' => 'acase_id_c',
	'ext2' => 'Cases',
	'module' => 'Cases',
	'rname' => 'new_case_number_c',
	'quicksearch' => 'enabled',
	'studio' => 'visible',
);
 ?>