<?php
/**
 *
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 *
 * SuiteCRM is an extension to SugarCRM Community Edition developed by SalesAgility Ltd.
 * Copyright (C) 2011 - 2017 SalesAgility Ltd.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo and "Supercharged by SuiteCRM" logo. If the display of the logos is not
 * reasonably feasible for  technical reasons, the Appropriate Legal Notices must
 * display the words  "Powered by SugarCRM" and "Supercharged by SuiteCRM".
 */

$dictionary['MTS_Medical_Treatment_Summary'] = array(
    'table' => 'mts_medical_treatment_summary',
    'audited' => true,
    'inline_edit' => true,
    'fields' => array (
  'treatment_date' => 
  array (
    'required' => false,
    'name' => 'treatment_date',
    'vname' => 'LBL_TREATMENT_DATE',
    'type' => 'date',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => 'Date of Treatment',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'enable_range_search' => false,
  ),
  'account_id_c' => 
  array (
    'required' => false,
    'name' => 'account_id_c',
    'vname' => 'LBL_MEDICAL_PROVIDER_ORGANIZATION_ACCOUNT_ID',
    'type' => 'id',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => 0,
    'audited' => false,
    'inline_edit' => true,
    'reportable' => false,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 36,
    'size' => '20',
  ),
  'medical_provider_organization' => 
  array (
    'required' => false,
    'source' => 'non-db',
    'name' => 'medical_provider_organization',
    'vname' => 'LBL_MEDICAL_PROVIDER_ORGANIZATION',
    'type' => 'relate',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => 'This is the facility where the treatment was provided',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
    'id_name' => 'account_id_c',
    'ext2' => 'Accounts',
    'module' => 'Accounts',
    'rname' => 'name',
    'quicksearch' => 'enabled',
    'studio' => 'visible',
  ),
  'contact_id_c' => 
  array (
    'required' => false,
    'name' => 'contact_id_c',
    'vname' => 'LBL_MEDICAL_PROVIDER_PERSON_CONTACT_ID',
    'type' => 'id',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => 0,
    'audited' => false,
    'inline_edit' => true,
    'reportable' => false,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 36,
    'size' => '20',
  ),
  'medical_provider_person' => 
  array (
    'required' => false,
    'source' => 'non-db',
    'name' => 'medical_provider_person',
    'vname' => 'LBL_MEDICAL_PROVIDER_PERSON',
    'type' => 'relate',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => 'This is the Name of the Person who provided the treatment',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
    'id_name' => 'contact_id_c',
    'ext2' => 'Contacts',
    'module' => 'Contacts',
    'rname' => 'name',
    'quicksearch' => 'enabled',
    'studio' => 'visible',
  ),
  'treatment_description_summary' => 
  array (
    'required' => false,
    'name' => 'treatment_description_summary',
    'vname' => 'LBL_TREATMENT_DESCRIPTION_SUMMARY',
    'type' => 'text',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => 'This is the summary of the treatment that occurred on this one date of treatment',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'studio' => 'visible',
    'rows' => '10',
    'cols' => '30',
  ),
  'treatment_work_product_note' => 
  array (
    'required' => false,
    'name' => 'treatment_work_product_note',
    'vname' => 'LBL_TREATMENT_WORK_PRODUCT_NOTE',
    'type' => 'text',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => 'This information is our attorney work product and not to be shared with anyone outside the law firm.',
    'help' => 'This is where we record notes or problems that the attorney needs to know about regarding problems, inconsistencies, or other concerns in this record',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'studio' => 'visible',
    'rows' => '4',
    'cols' => '20',
  ),
  'cpt_codes_treatment' => 
  array (
    'required' => false,
    'name' => 'cpt_codes_treatment',
    'vname' => 'LBL_CPT_CODES_TREATMENT',
    'type' => 'text',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => 'This is a list of the CPT Codes the medical provider listed for this treatment date.',
    'help' => 'Enter all CPT Codes for this Treatment',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'studio' => 'visible',
    'rows' => '4',
    'cols' => '20',
  ),
  'icd_codes' => 
  array (
    'required' => false,
    'name' => 'icd_codes',
    'vname' => 'LBL_ICD_CODES',
    'type' => 'text',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => 'Enter the ICD codes here',
    'help' => 'This is where we record the ICD Codes used by the medical provider to define the diagnosis',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'studio' => 'visible',
    'rows' => '4',
    'cols' => '20',
  ),
  'symptom_1' => 
  array (
    'required' => false,
    'name' => 'symptom_1',
    'vname' => 'LBL_SYMPTOM_1',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => 'First Main Symptom',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'symptom_1_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'pain_scale' => 
  array (
    'required' => false,
    'name' => 'pain_scale',
    'vname' => 'LBL_PAIN_SCALE',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => 'If Pain is measured, put the measurement next to the symptom',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'pain_scale_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'symptom_other' => 
  array (
    'required' => false,
    'name' => 'symptom_other',
    'vname' => 'LBL_SYMPTOM_OTHER',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => 'Add any other symptoms that don&#039;t fit the drop down list',
    'help' => 'Other Symptoms that don\'t fit the drop down list',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'symptom_2' => 
  array (
    'required' => false,
    'name' => 'symptom_2',
    'vname' => 'LBL_SYMPTOM_2',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => 'Second Symptom Listed in the Treatment Record',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'symptom_1_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'symptom_3' => 
  array (
    'required' => false,
    'name' => 'symptom_3',
    'vname' => 'LBL_SYMPTOM_3',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => 'Third Symptom in the Treatment Record',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'symptom_1_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'symptom_4' => 
  array (
    'required' => false,
    'name' => 'symptom_4',
    'vname' => 'LBL_SYMPTOM_4',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => 'Fourth Symptom',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'symptom_1_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'symptom_5' => 
  array (
    'required' => false,
    'name' => 'symptom_5',
    'vname' => 'LBL_SYMPTOM_5',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'symptom_1_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'symptom_6' => 
  array (
    'required' => false,
    'name' => 'symptom_6',
    'vname' => 'LBL_SYMPTOM_6',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'symptom_1_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'symptom_7' => 
  array (
    'required' => false,
    'name' => 'symptom_7',
    'vname' => 'LBL_SYMPTOM_7',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'symptom_1_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'symptom_8' => 
  array (
    'required' => false,
    'name' => 'symptom_8',
    'vname' => 'LBL_SYMPTOM_8',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'symptom_1_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'symptom_9' => 
  array (
    'required' => false,
    'name' => 'symptom_9',
    'vname' => 'LBL_SYMPTOM_9',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'symptom_1_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'symptom_10' => 
  array (
    'required' => false,
    'name' => 'symptom_10',
    'vname' => 'LBL_SYMPTOM_10',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'symptom_1_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'pain_scale_2' => 
  array (
    'required' => false,
    'name' => 'pain_scale_2',
    'vname' => 'LBL_PAIN_SCALE_2',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'pain_scale_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'pain_scale_3' => 
  array (
    'required' => false,
    'name' => 'pain_scale_3',
    'vname' => 'LBL_PAIN_SCALE_3',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'pain_scale_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'pain_scale_4' => 
  array (
    'required' => false,
    'name' => 'pain_scale_4',
    'vname' => 'LBL_PAIN_SCALE_4',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'pain_scale_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'pain_scale_5' => 
  array (
    'required' => false,
    'name' => 'pain_scale_5',
    'vname' => 'LBL_PAIN_SCALE_5',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'pain_scale_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'pain_scale_6' => 
  array (
    'required' => false,
    'name' => 'pain_scale_6',
    'vname' => 'LBL_PAIN_SCALE_6',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'pain_scale_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'pain_scale_7' => 
  array (
    'required' => false,
    'name' => 'pain_scale_7',
    'vname' => 'LBL_PAIN_SCALE_7',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'pain_scale_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'pain_scale_8' => 
  array (
    'required' => false,
    'name' => 'pain_scale_8',
    'vname' => 'LBL_PAIN_SCALE_8',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'pain_scale_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'pain_scale_9' => 
  array (
    'required' => false,
    'name' => 'pain_scale_9',
    'vname' => 'LBL_PAIN_SCALE_9',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'pain_scale_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'pain_sclae_10' => 
  array (
    'required' => false,
    'name' => 'pain_sclae_10',
    'vname' => 'LBL_PAIN_SCLAE_10',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'pain_scale_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'pain_scale_other' => 
  array (
    'required' => false,
    'name' => 'pain_scale_other',
    'vname' => 'LBL_PAIN_SCALE_OTHER',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'pain_scale_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'missing_record_we_need_to_get' => 
  array (
    'required' => false,
    'name' => 'missing_record_we_need_to_get',
    'vname' => 'LBL_MISSING_RECORD_WE_NEED_TO_GET',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => 'When we review a treatment, we may find another medical provider or service was done and we don&#039;t have those records.  Record the record we need to get here and this will create a Task to get those records',
    'help' => 'When looking at a treatment note, you may find another medical provider mentioned, and we need to get those records too, please add the name and type of record here',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
 'summary_title_list' => 
  array (
    'required' => true,
    'name' => 'summary_title_list',
    'vname' => 'LBL_SUMMARY_TITLE_LIST',
    'type' => 'enum',
    'options' => 'summary_title_list_dom',
  ), 
  'show_file_first' => 
  array (
    'name' => 'show_file_first',
    'vname' => 'LBL_SHOW_FILE_FIRST',
    'type' => 'bool',
  ),
),
    'relationships' => array (
),
    'optimistic_locking' => true,
    'unified_search' => true,
);
if (!class_exists('VardefManager')) {
        require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('MTS_Medical_Treatment_Summary', 'MTS_Medical_Treatment_Summary', array('basic','assignable','security_groups','file'));